<div class="container">
    <div class="row">
        <div class="col-xs-5">
            <h4>Formulario de Atualização</h4>
            <form class="" method="post"
                  action="/application/index/create"" class="form-control">
                <div class="form-group">
                    <label for="nome">Nome:</label>
                    <input type="text" name="nome" required id="nome" class="form-control">
                </div>
                <div class="form-group">
                    <label for="endereco">Endereço:</label>
                    <input type="text" name="endereco" required id="endereco" class="form-control">
                </div>
                <div class="form-group">
                    <label for="numero">Numero:</label>
                    <input type="text" name="numero" required id="numero" class="form-control">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">Cadastrar</button>
                    <a href="/application/index/index" type="submit" class="btn btn-danger">Cancelar</a>
                </div>
            </form>

        </div>
    </div>
</div>